### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by BenHall** [gurumitts/pylutron-caseta#111]
I understand everyone is busy, but I was wondering when the RA3 work will be released as then available in Home Assistant? 

Is there a formal process/timeline? 

Is there anything I can do to help?

**Comment by danaues** [comment]
@BenHall, I'm not sure on the timelline or process for releasing a new version of pylutron-caseta, but assuming we can do this in the next few weeks, then I think a reasonable expectation is to make the HA October beta , and hopefully ready for the HA November release.

**Comment by danaues** [comment]
If you want to help test the unreleased code, please check out this thread.
https://github.com/danaues/pylutron-caseta/issues/7

**Comment by mdonoughe** [comment]
[v0.15.0](https://pypi.org/project/pylutron-caseta/0.15.0/) released today.

**Comment by danaues** [comment]
@mdonoughe , we have a small naming issue for keypads that was introduced in the last PR.  Keypads are getting one of the button names appended to the device name as a result of the way the HA devices are created from the button list.  Perhaps we should fix this before releasing, or do a 0.15.1 release to address?  @bdraco is about to bump the version in HA dev

**Comment by danaues** [comment]
more detail:

It will affect RA3/QSX Only. The keypad device name will have one of the button names appended to it, due to the way the devices are generated. ie “Upstairs_Hallway_Position_1_SunnataKeypad” is being named as (either first or last button not sure yet) due to the way the device registry is done. The keypad ends up incorrectly being named “Upstars_Hallway_position_1_SunnatKeypad_Button_1”.

This button name change was introduced to support button presses, which is not fully implemented yet. Caseta buttons are named the same as the keypad, so the problem doesn’t exist.

I think we temporary need to rename the buttons to match the keypad. Then re-apply once pylutron-caseta and lutron-caseta are ready for the button entities.

**Comment by danaues** [comment]
discussion here:
https://github.com/home-assistant/core/pull/78209
