### ISSUE TITLE
New method no longer working?

### ISSUE THREAD

**Issue by xnappo** [gurumitts/pylutron-caseta#22]
I appears that something has changed on the Lutron end.  Neither the plugin nor the script to get a key are working anymore.

plugin error:
`Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/lutron_caseta.py", line 57, in async_setup
    yield from bridge.connect()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 40, in connect
    yield from self._login()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 281, in _login
    self._reader, self._writer = yield from self._connect()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 58, in _connect
    family=socket.AF_INET)
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/leap.py", line 16, in open_connection
    limit=limit, **kwds)
  File "/usr/lib/python3.6/asyncio/streams.py", line 75, in open_connection
    lambda: protocol, host, port, **kwds)
  File "uvloop/loop.pyx", line 1769, in create_connection
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)`

Script error:
`(general) xnappo@machine:~/homeio$ python get_lutron_cert.py
Enter the address of your Caseta bridge device: 192.168.1.xx
Traceback (most recent call last):
  File "get_lutron_cert.py", line 156, in <module>
    leap_response['Body']['PingResponse']['LEAPVersion'])
KeyError: 'Body'`

**Comment by xnappo** [comment]
At least looking at the script, possibly this is an easy fix and the responses have just changed?  The get script is returning this for 'leap_response' now:

`Response: {'CommuniqueType': 'SubscribeResponse', 'Header': {'StatusCode': '204 NoContent', 'Url': '/device/status/deviceheard'}}`

**Comment by jeffphilly** [comment]
yea mine seems to have stopped working as well. Hopefully someone can figure this out, or my HA is gonna have a huge problem

**Comment by holelattanuttin** [comment]
When you say mine has stopped working, you mean enrollment to get certificates?

**Comment by jeffphilly** [comment]
i am getting an error that says "invalid config"

**Comment by holelattanuttin** [comment]
Did a restart trigger this?

**Comment by jeffphilly** [comment]
yes i did a restart of HA and then it came up

**Comment by holelattanuttin** [comment]
Is there anything in the home-assistant.log?

**Comment by holelattanuttin** [comment]
I am only asking because mine is still working.  I am on HA 0.65.6

**Comment by BillyPrefect** [comment]
Damn power outage.  I wondered what happened, google led me here.

**Comment by xnappo** [comment]
I am moving to a Pro which will work with this: https://github.com/upsert/lutron-caseta-pro

**Comment by holelattanuttin** [comment]
xnappo, I don't know if this is the proper venue, but let us know how it goes.

**Comment by holelattanuttin** [comment]
@jeffphilly How many devices did you have and what type(s)?

**Comment by BillyPrefect** [comment]
Googling and scouring... I just realized that I can skip the hub and use my Wink ver 1 controller to control the two switches I've go, and send them to HASSIO through Wink instead. 
I think.

**Comment by jeffphilly** [comment]
@jchong its probably gonna get fixed, but it seems like it will eventually break unless luton decides to do the right thing. I bought the pro hub and it honestly looks like the exact same thing. What we really need is someone to figure out how to convert the regular hub to the pro hub if possible.

**Comment by sfnetwork** [comment]
I'm new to HA and have a lot of Lutron Caseta with standard hub.
I fully understand the reason why HA is trying to "keep up" with Lutron changes.
My question is more; is this happening often? (Lutron making changes that break HA method)
How often in a year usually, Lutron breaks HA method?
I'm asking because if this happens like several times per year, I won't rely on it and need to make changes...
I'm not going to change the bridge, waste of money, no real advantage vs the standard. (if I wouldn't have any hub, of course I would take the pro)
And looking at the Pro specs and compare to standard from Lutron web site, there is nothing that I saw about open API, etc... no how certain are we that Pro won't break as well?

I really understand there is no guaranty of anything here, just trying to find the most stable and reliable path...

**Comment by xnappo** [comment]
@jeffphilly - yeah, but converting might be difficult to maintain.  If Lutron is smart, they will have the MAC addresses in the cloud, so not only would one need to figure out how to program the Pro firmware on the non-pro, but also block the cloud from re-flashing the firmware.  From teardowns I have seen though - they are using external flash - which means it would likely not be all that hard to get at the firmware with a little dedication.

**Comment by jeffphilly** [comment]
@xnappo This is way outside of my skill set, it just seems a bit ridiculous that they are essentially charging more so that we can get get a software update. I am so over and proprietary smart home software

**Comment by sknolin** [comment]
It's most likely Lutron simply changed how they do ssl slightly, or have a new pki infrastructure or something. The last time this happened they went from using a method that was pretty insecure (the private ssh key was available, and used globally, it was hilarious) to a more normal public key infrastructure type method for ssl. 

My guess is the homeassistant usage is such a slim portion of their business, it's simply not something they're going to test against.

The pro version uses the completely plaintext telnet protocol, with a known username and password (thought I think Lutron does try to quash the username/password information in their forum). So the non-pro version is more secure. So with a pro hub someone can just roll up to a house and start playing with lutron devices. Hope it's not a security system :) https://forums.lutron.com/showthread.php/1076-Telnet-Username-and-Password

It's quite ironic that the pro version will break less often, because they can't easily change it and screw up all their integrators.

All that said, it's a drag.

**Comment by holelattanuttin** [comment]
I broke down and I got a Pro.  The most time consuming part is any groups and customizations that were configured, of course, but if you make sure and delete all devices before removing your account, everything should be fine.  A very fine custom component.  Maybe I can relax for awhile...

**Comment by jeffphilly** [comment]
Yea the setting up was annoying, but glad I don’t have to worry about it hopefully.

**Comment by xnappo** [comment]
Yeah, just set mine up too.  Not a big deal and the telnet access is obviously supported since it is in the app.  Hopefully can sell the non-pro on ebay for $30 or so and not be out too much.  I needed another dimmer anyway.

**Comment by BillyPrefect** [comment]
My Wink controls the dimmers only ok.  Long delay between Hey Alexa and the light actually reacting, a solid second or two even.  It does work though, and as I already had the Wink ver 1, I'm not out the $150ish here in Canada.

**Comment by mattya802** [comment]
Man, I would really love an update on this. Light control is one of the main benefits of HA.....

**Comment by mdonoughe** [comment]
I'm getting this too now. I'll look into fixing it.

**Comment by jeffphilly** [comment]
@mattya802 i switched to Pro Hub. Working as before. Money but at least everything works again.

**Comment by xnappo** [comment]
Pro Hub uses telnet, which is an option in the app for 3rd party control.  Not a 100% guarantee but other 3rd party apps and custom installers rely on it.

**Comment by msmith9xr4** [comment]
I'm also in this boat... Passed Lutron to Vera, now gone. HA, semi-gone. Wink- at least the metal in licenced. Let's think in 2-3 years when most of the battle is done, we just need lutron protocol HW support, or bridging WINK.  As long as there are wink or caseta devices with radio access to devices, we're not lost. 

Lutron has sent em encouraging messages that suggest they are not trying to make their products poisonous. They will allow interfacing.

Wink and pro are last resort ways of keeping manual control on immense lutron investment. IT seems clear that Lutron and MS and hoping to make investments obsolete,

Only the next worlds will tell.

**Comment by sfnetwork** [comment]
ok, it's working again (non pro)
I simply modified I simply modified "smartbridge.py" from the PR.

**Comment by gurumitts** [comment]
This is fixed in version 0.5.  https://pypi.org/project/pylutron_caseta/

**Comment by mattya802** [comment]
So what does that mean for us HA users? How do we go about updating and fixing HA?

**Comment by gurumitts** [comment]
We need to push changes to the HA project and update this dependency.

**Comment by rohankapoorcom** [comment]
I opened a pull request with homeassistant to bump the library version: https://github.com/home-assistant/home-assistant/pull/14013

**Comment by rohankapoorcom** [comment]
@gurumitts, we should be good to close this out now right?

**Comment by biochemguy** [comment]
@gurumitts I still have the same problem as @xnappo. As I am new to HA and I am trying to setup my lutron device, I am getting the same error when I use the get_lutron.py  tool:

get_lutron_cert.py Enter the address of your Caseta bridge device: 192.168.1.xx Traceback (most recent call last): File "get_lutron_cert.py", line 156, in <module> leap_response['Body']['PingResponse']['LEAPVersion']) KeyError: 'Body'. 

I think that the  get_lutron.py might also need to be updated to reflect the lutron's new login changes. Any help would be appreciated.

**Comment by mdonoughe** [comment]
Try the version of the script here: https://github.com/gurumitts/pylutron-caseta/blob/master/get_lutron_cert.py

The Home Assistant documentation likely needs updating still.

**Comment by biochemguy** [comment]
Thanks for the support! I did not realize that the file was not linked and updated directly from the Home Assistant documentation. This worked to generate the files. 

I copied the generated files to the configuration folder with my configuration.yaml and updated the pylutron_caseta to 0.5.0 on my system, but still gives me this error:

> 2018-04-24 09:11:44 ERROR (MainThread) [homeassistant.setup] Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/lutron_caseta.py", line 57, in async_setup
    yield from bridge.connect()
  File "/srv/homeassistant/lib/python3.5/site-packages/pylutron_caseta/smartbridge.py", line 40, in connect
    yield from self._login()
  File "/srv/homeassistant/lib/python3.5/site-packages/pylutron_caseta/smartbridge.py", line 284, in _login
    yield from self._load_devices()
  File "/srv/homeassistant/lib/python3.5/site-packages/pylutron_caseta/smartbridge.py", line 314, in _load_devices
    for device in device_json['Body']['Devices']:
KeyError: 'Body'
> 

Sorry, I am not sure if this needs to be in a new thread?

Any ideas?

Thanks

**Comment by mdonoughe** [comment]
That sounds like you may still be running the old version of the code. Home Assistant tries to restore packages on startup unless you pass `--skip-pip` and may have put the old version back where it was or into config/deps.

**Comment by biochemguy** [comment]
Thanks for the feedback. I did  not know that home assistant was looking for the previous versions. I tried a few things in homeassistant to force the new version and found a way that worked with `--skip-pip`.

I had to find the install location of pylutron_caseta, because a simple install or upgrade did not change the file version within home assistant:
` pip show pylutron_caseta`
I then upgraded the file in the location found using:
`sudo pip install --upgrade pylutron_caseta==0.5.0 --target /srv/homeassistant/lib/python3.5/site-packages`
Finally I was able to start homeassistant with 
`hass -c /home/homeassistant/.homeassistant/ --skip-pip`

AND IT WORKED!!! THANKS!

**Comment by bwoodworth** [comment]
I am still struggling to get this working in hassio.  I have copied the new version of lutron_caseta.py to the custom_components directory and restarted hassio and I still get the error in the log:

Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/config/custom_components/lutron_caseta.py", line 57, in async_setup
    yield from bridge.connect()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 40, in connect
    yield from self._login()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 284, in _login
    yield from self._load_devices()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 314, in _load_devices
    for device in device_json['Body']['Devices']:
KeyError: 'Body'

Can someone help me get this working in hassio?

**Comment by fremgenc** [comment]
From scratch, using the newest script from 

https://github.com/gurumitts/pylutron-caseta/blob/master/get_lutron_cert.py


```
Traceback (most recent call last):
  File "get_lutron_cert.py", line 124, in <module>
    app_cert = pairing_response["remote_signs_app_certificate"]
KeyError: 'remote_signs_app_certificate'

```

**Comment by sjakub** [comment]
I am seeing the same error as @fremgenc 
I modified the script a little, to show me what's the actual response from the server.
It looks like the script is POSTing to https://device-login.lutron.com/api/v1/remotepairing/application/user
and it's getting 400 error code.
The data sent in that response is just "{}", so empty JSON.
And, since it's empty, there is no "remote_signs_app_certificate" key in it...

**Comment by mdonoughe** [comment]
Can we close this? There was separate issue raised and closed for get_lutron_cert.py: #26

**Comment by sjakub** [comment]
Still doesn't work for me...

**Comment by mdonoughe** [comment]
What version of the script are you using? Are you able to control your devices from your phone? Are you logging into the Lutron site to get a new authentication token every time? Is it any different if you use this script? https://github.com/mdonoughe/pylutron-caseta/blob/content-type/get_lutron_cert.py

**Comment by cfremgen** [comment]
New script worked for me. Thanks guys.

If it helps anyone in the future, I was logging in with an old account. If your response is empty, make sure you have devices hooked up to the account you're logging in with.

**Comment by sjakub** [comment]
I just tried this: https://github.com/mdonoughe/pylutron-caseta/blob/content-type/get_lutron_cert.py
Same error, "KeyError: 'remote_signs_app_certificate'".
And I just changed a password on my account, logged out in the app and logged back in - using the new password. I tried the script and used that link in a different browser that wouldn't have any cookies for that and using the new password. Same error. I am able to control things using the phone app, even when I'm not on my home Wi-Fi.

Also, in the meantime, I found another home assistant plugin that requires pro bridge (that's what I have, maybe that's the difference?) and copying the integration report manually, but it works.

**Comment by mdonoughe** [comment]
I don't have a pro bridge and I don't know if this is supposed to work with the pro bridge.

**Comment by mdonoughe** [comment]
If you want to try, you should load Android M or earlier in the Android emulator, set up mitmproxy, and record what happens when you log in with the app. Hopefully you will see an oauth sign in and then a request to sign a certificate. `get_lutron_cert.py` is supposed to emulate this exchange.

If that isn't happening, it's possible the pro hub doesn't use leap over tls the same way as the normal hub. You can try checking that with wireshark.

It's possible to do this on Android N and later, but it's more complicated because of changes to the way certificate authorities are handled.

**Comment by jaboutboul** [comment]
Hi All. Any update on this issue? Anyone working on resolving it?

**Comment by stbenjam** [comment]
Just started getting this after a power outage and the hub rebooted. Any idea how to fix it?

I reissued certificates with the script and it worked, and even reported Successfully connected to bridge, running LEAP Server version 1.108, but home assistant is still unhappy.

**Comment by stbenjam** [comment]
The CA cert in caseta-bridge.crt no longer seems to match, setting ssl.CERT_NONE in smartbridge.py fixes the error and HA is working again, but I haven't been able to investigate any further than that.  Something changed when I rebooted the hub.

**Comment by jumblies** [comment]
Here we go again.  I really wish lutron had some notification channel when they pull crap like this.
