### ISSUE TITLE
Lutron Caseta firmware updte ?

### ISSUE THREAD

**Issue by Breakerz** [gurumitts/pylutron-caseta#28]
I think Lutron update his firmware...  
The HA component stop working : https://github.com/home-assistant/home-assistant/issues/15421

Why get_lutron_certificate.py, if i dump the json result of the test request, i got that : 

`{'Header': {'StatusCode': '204 NoContent', 'Url': '/device/status/deviceheard'}, 'CommuniqueType': 'SubscribeResponse'}`

**Comment by mdonoughe** [comment]
I can try rebooting mine this weekend and see if I can get it working again.

**Comment by mdonoughe** [comment]
"SubscribeResponse" sounds familiar. Are you running the get_lutron_certificate from this repo or the one in the Home Assistant docs? I originally put it in the Home Assistant documentation, but then copied it over to this repository when I needed to update it for the last firmware update, but somebody else did the update for Home Assistant that time and the documentation didn't get updated to use the new script. I was going to do that when adding component registry support, but I wanted to also close out #22 for sure.

My bridge disconnected at 6:30 today, and due to #19 I had to restart Home Assistant but my lights are still working for now. I'll still try rebooting this weekend to see if there's a new update that breaks it.

**Comment by Breakerz** [comment]
quick fix : 
in  [ /srv/hass/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py  ]  line 50 : 
`ssl_context.verify_mode = ssl.CERT_OPTIONAL `

instead of 
`ssl_context.verify_mode = ssl.CERT_REQUIRED`

**Comment by jcuccia** [comment]
I know that "it works for me" isn't terribly useful, but I thought I'd add a data point. 

I brought up a new instance of HASS.IO/HASSOS (on RPi) for testing on Wednesday (7/11). After reading about this issue yesterday, I copied my Lutron certs from my production machine to the new HASS.IO setup and rebooted. The Lutron component configured correctly.  Note that I generated the certs on May 3, 2018 using the script in gurumitts repository.

Of course now I'm afraid to reboot my production machine <g>.

**Comment by mdonoughe** [comment]
When rerunning the script, make sure you remove any keys from last time. It tries to skip steps which isn't what you want if your certificates have changed.

**Comment by adamaze** [comment]
im having the same issue, and i just used the updated script to generate new certs, but still get the same error message

**Comment by blerrgh** [comment]
> When rerunning the script, make sure you remove any keys from last time. It tries to skip steps which isn't what you want if your certificates have changed.

Just tried it again after deleting all the cert and key files to double check, still have the same problem. :/

**Comment by kalex1114** [comment]
@jumblies where is the file located that you modified on hass.io installation?

**Comment by b3nj1** [comment]
@kalex1114 , I'm sure there's a better way, but this worked for me to find the file:

`sudo find / -name smartbridge.py`

In my case:
```
/var/lib/docker/overlay2/33803716ead58faca8ab56c49f6f362ec5059a86aef9cc8d81f8c150e40d23d8/diff/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py
/var/lib/docker/overlay2/e72b09633dfb75d1f9673de9b44a0bed9fd446e1f5aee22884dccdc4e2acfa70/merged/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py
```

They are linked, so editing one was sufficient.

Hope that helps.

**Comment by mdonoughe** [comment]
Can you try adding `server_hostname=''` to smartbridge.py like I did in 618deda instead of `ssl_context.verify_mode = ssl.CERT_NONE`? That fixes it for me.

Interestingly, I could only reproduce this issue on my desktop. My Home Assistant server is running an older version of the Home Assistant docker container and doesn't seem to be affected. It looks like a problem only if you're using a newer version of Python.

I wouldn't blame the engineers at Lutron. It would be nice if they had official APIs or libraries or even just a channel for communicating this kind of information, but these things would cost the company money and the number of people buying these switches to use in this way isn't going to be very compelling to the business. It looks like they're trying to implement a new feature and our unofficial client happened to break.

If you wanted to and your router supports it, it looks like you could completely remove your bridge's internet connection to stop firmware updates coming from outside and still control the bridge locally. I don't know if the phone app would ever try to push firmware updates over the local network.

**Comment by jumblies** [comment]
@kalex1114 
I'm sorry I can't help with that one.  Tried Hassio and really didn't like it so I run mine on metal on an Orange Pi Zero.  

@mdonoughe 
I'll try that and report back.  

Sorry about the rant, I just get tired of it changing so frequently.  I really like the hardware and I was too hard on them.  It's good kit.  Just frustrating when everything I've made is more robust than a commercial product and I suck at coding.  I'm also spoiled by Tasmota and MQTT which by comparison is VERY easy to troubleshoot.  When lutron fails, all I can do is sigh and stare a little white square that is a mystery to me.

**Comment by adamaze** [comment]
@mdonoughe
this fixed it for me. Thanks!

**Comment by blerrgh** [comment]
For what it's worth, in my case, things seem to have fixed themselves once I updated to 0.73.2.

**Comment by sfnetwork** [comment]
0.73.2 didn't fix it for me, had to do the workaround (ssl.CERT_NONE)

**Comment by sweharris** [comment]
Interesting; I'm on 0.89.2 and had to apply the @mdonoughe `server_hostname` fix

**Comment by darchambault** [comment]
Had the same issue after upgrading from 0.63.1 to 0.90.1, and the `server_hostname=''` change fixed this for me!
