### ISSUE TITLE
Trying to find AssociatedDevices on OccupancyGroup instead of Area

### ISSUE THREAD

**Issue by jmoor3** [gurumitts/pylutron-caseta#57]
I think the concepts of "Area" and "OccupancyGroup" are reversed. From what I'm seeing it's rejecting OccupancyGroups because there are no AssociatedDevice[s] but those are assigned to Area[s].

https://github.com/gurumitts/pylutron-caseta/blob/b6ffcf61dff3d0e2da5181bb714f6a76ec1901ae/pylutron_caseta/smartbridge.py#L526

`Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.smartbridge] Loading areas from the Smart Bridge
Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.leap] sending b'{"CommuniqueType": "ReadRequest", "Header": {"Url": "/area"}}'
Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.leap] received b'{"CommuniqueType":"ReadResponse","Header":{"MessageBodyType":"MultipleAreaDefinition","StatusC
ode":"200 OK","Url":"/area"},"Body":{"Areas":[{"href":"/area/1","Name":"root","LoadShedding":{"href":"/area/1/loadshedding"}},{"href":"/area/2","Name":"Dining Room","Parent":{"href":"/area/1"},"Category":{"Ty
pe":"DiningRoom"},"AssociatedDevices":[{"href":"/device/2"},{"href":"/device/3"},{"href":"/device/22"},{"href":"/device/24"},{"href":"/device/25"}],"AssociatedOccupancyGroups":[{"href":"/occupancygroup/1"}],"
LoadShedding":{"href":"/area/2/loadshedding"},"OccupancySettings":{"href":"/area/2/occupancysettings"},"OccupancySensorSettings":{"href":"/area/2/occupancysensorsettings"},"DaylightingGainSettings":{"href":"/
area/2/daylightinggainsettings"}},
...`

`Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.smartbridge] Loading occupancy groups from the Smart Bridge
Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.leap] sending b'{"CommuniqueType": "ReadRequest", "Header": {"Url": "/occupancygroup"}}'
Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.leap] received b'{"CommuniqueType":"ReadResponse","Header":{"MessageBodyType":"MultipleOccupancyGroupDefinition
","StatusCode":"200 OK","Url":"/occupancygroup"},"Body":{"OccupancyGroups":[{"href":"/occupancygroup/1","AssociatedAreas":[{"Area":{"href":"/area/2"}}],"ProgrammingType":"Freeform","ProgrammingModel":{"href":
"/programmingmodel/142"}},{"href":"/occupancygroup/2","AssociatedAreas":[{"Area":{"href":"/area/3"}}],"ProgrammingType":"Freeform","ProgrammingModel":{"href":"/programmingmodel/143"}},{"href":"/occupancygroup
/3","AssociatedAreas":[{"Area":{"href":"/area/4"}}],"ProgrammingType":"Freeform","ProgrammingModel":{"href":"/programmingmodel/144"}},{"href":"/occupancygroup/4","AssociatedAreas":[{"Area":{"href":"/area/5"}}
],"ProgrammingType":"Freeform","ProgrammingModel":{"href":"/programmingmodel/145"}},{"href":"/occupancygroup/5","AssociatedAreas":[{"Area":{"href":"/area/6"}}],"ProgrammingType":"Freeform","ProgrammingModel":
{"href":"/programmingmodel/146"}},{"href":"/occupancygroup/6","AssociatedAreas":[{"Area":{"href":"/area/7"}}],"ProgrammingType":"Freeform","ProgrammingModel":{"href":"/programmingmodel/157"}},{"href":"/occupa
ncygroup/7","AssociatedAreas":[{"Area":{"href":"/area/8"}}],"ProgrammingType":"Freeform","ProgrammingModel":{"href":"/programmingmodel/158"}},{"href":"/occupancygroup/8","AssociatedAreas":[{"Area":{"href":"/a
rea/9"}}],"ProgrammingType":"Freeform","ProgrammingModel":{"href":"/programmingmodel/159"}},{"href":"/occupancygroup/9",
...
Sep 14 13:32:42 raspberrypi hass[14890]: 2020-09-14 13:32:42 DEBUG (MainThread) [pylutron_caseta.smartbridge] No sensors associated with /occupancygroup/1
`

**Comment by swails** [comment]
I'm not exactly sure what you mean here.  If there are no `AssociatedDevices`, then that means that there are no devices responding to changes in occupancy state for that occupancy group.  Strictly within the Caseta or RA2 Select system, having such an occupancy group makes no sense.  In the context of Home Assistant, however, it allows you use Lutron Occupancy sensors to control other smart home products (smart bulbs, smart plugs, garage door if you feel like being crayzay, etc.).

However, it should be impossible to add an occupancy/vacancy sensor to a Caseta system without putting it in an area.  As a result, any occupancy group that has at least one sensor must have an associated area.  So a situation where there is no associated area with an occ group that has 1+ sensors represents some kind of system corruption.  That's why the piece of logic you highlighted is there.

**Comment by jmoor3** [comment]
Sorry I mixed up two things. I wanted AssociatedDevices to areas loaded in so I can pass them through to HomeAssistant. Didn't realize this was looking for Associated*Sensors* which are associated with occupancygroups. I'm doing a local change to pull in AssociatedDevices and closed this out and will send a pull req if it ends up being useful.

**Comment by swails** [comment]
What are you doing with associated devices?  Those are just the devices that respond to occupancy state changes in some way.  Home Assistant probably won't care much about that (especially since HA can't really change any of that behavior).

What I'm doing with my HA system is I have 2 occupancy sensors in my bathroom configured in vacancy mode (upon going vacant, the bathroom lights turn off) -- this is handled by Caseta.  With Home Assistant, I have a transition to the 'occupied' state trigger a 'bright' scene between sunrise and 10:30pm, a 'very dim' scene between 10:30pm and 5:30am, and a 'medium dim' scene between 5:30am and sunrise.  That part can't be done purely within Caseta, which is why I added support for occ sensors in the first place.

**Comment by jmoor3** [comment]
I'm trying to create groups out of the rooms I make in the lutron app
automatically in homeassistant. I was under the impression that Area
represents effectively a "room" in the Lutron app.
